export { Navbar } from '@/scenes/navbar/Navbar'
export { Home } from '@/scenes/home/Home'
export { Benefits } from '@/scenes/benefits/Benefits'
export { OurClasses } from '@/scenes/ourClasses/OurClasses'
export { ContactUs } from '@/scenes/contactUs/ContactUs'
